# Generated by Django 5.0.2 on 2024-03-12 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0002_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='id_usuario',
            new_name='id',
        ),
    ]
